name: android-gh
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build GH APK (release)
        working-directory: TalaaGHApp/android
        run: |
          chmod +x gradlew || true
          ./gradlew assembleRelease --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: talaaGH-apk
          path: TalaaGHApp/android/app/build/outputs/apk/release/*.apk
